INSERT INTO `tblitem`(`ID`, `category_ID`, `name`, `displayname`, `picture`, `unit`, `price`) VALUES ('',1,'greenamaranthus','Green Amaranthus (mchicha)','images/vegetables/greenamaranthus.jpg','bunch',500);
INSERT INTO `tblitem`(`ID`, `category_ID`, `name`, `displayname`, `picture`, `unit`, `price`) VALUES ('',1,'redamaranthus','Red Amaranthus (mchicha)','images/vegetables/redamaranthus.jpg','bunch',500);
INSERT INTO `tblitem`(`ID`, `category_ID`, `name`, `displayname`, `picture`, `unit`, `price`) VALUES ('',1,'avocados','Avocados','images/vegetables/avocados.jpg','piece',1000);
INSERT INTO `tblitem`(`ID`, `category_ID`, `name`, `displayname`, `picture`, `unit`, `price`) VALUES ('',1,'redbeetroot','Red Beetroot','images/vegetables/redbeetroot.jpg','kg',5500);
INSERT INTO `tblitem`(`ID`, `category_ID`, `name`, `displayname`, `picture`, `unit`, `price`) VALUES ('',1,'greenbellpeppers','Green Bell Peppers','images/vegetables/greenbellpeppers.jpg','kg',2500);
INSERT INTO `tblitem`(`ID`, `category_ID`, `name`, `displayname`, `picture`, `unit`, `price`) VALUES ('',1,'redbellpeppers','Red Bell Peppers','images/vegetables/redbellpeppers.jpg','kg',10000);
INSERT INTO `tblitem`(`ID`, `category_ID`, `name`, `displayname`, `picture`, `unit`, `price`) VALUES ('',1,'broccoli','Broccoli','images/vegetables/broccoli.jpg','kg',5000);
INSERT INTO `tblitem`(`ID`, `category_ID`, `name`, `displayname`, `picture`, `unit`, `price`) VALUES ('',1,'butternutsquash','Butternut Squash','images/vegetables/butternutsquash.jpg','kg',3000);
INSERT INTO `tblitem`(`ID`, `category_ID`, `name`, `displayname`, `picture`, `unit`, `price`) VALUES ('',1,'cabbage','Cabbage','images/vegetables/cabbage.jpg','piece',1500);
INSERT INTO `tblitem`(`ID`, `category_ID`, `name`, `displayname`, `picture`, `unit`, `price`) VALUES ('',1,'redcabbage','Red Cabbage','images/vegetables/redcabbage.jpg','kg',3500);
INSERT INTO `tblitem`(`ID`, `category_ID`, `name`, `displayname`, `picture`, `unit`, `price`) VALUES ('',1,'carrot','Carrots','images/vegetables/carrot.jpg','kg',2000);
INSERT INTO `tblitem`(`ID`, `category_ID`, `name`, `displayname`, `picture`, `unit`, `price`) VALUES ('',1,'cauliflower','Cauliflower','images/vegetables/cauliflower.jpg','kg',3000);
INSERT INTO `tblitem`(`ID`, `category_ID`, `name`, `displayname`, `picture`, `unit`, `price`) VALUES ('',1,'celery','Celery','images/vegetables/celery.jpg','bunch',1000);
INSERT INTO `tblitem`(`ID`, `category_ID`, `name`, `displayname`, `picture`, `unit`, `price`) VALUES ('',1,'greenchilies','Green Chilies','images/vegetables/greenchilies.jpg','kg',5000);
INSERT INTO `tblitem`(`ID`, `category_ID`, `name`, `displayname`, `picture`, `unit`, `price`) VALUES ('',1,'habanerochilies','Habanero Chilies','images/vegetables/habanerochilies.jpg','kg',5000);
INSERT INTO `tblitem`(`ID`, `category_ID`, `name`, `displayname`, `picture`, `unit`, `price`) VALUES ('',1,'redchilies','Red Chilies','images/vegetables/redchilies.jpg','kg',5000);
INSERT INTO `tblitem`(`ID`, `category_ID`, `name`, `displayname`, `picture`, `unit`, `price`) VALUES ('',1,'chinesecabbage','Chinese Cabbage','images/vegetables/chinesecabbage.jpg','bunch',500);
INSERT INTO `tblitem`(`ID`, `category_ID`, `name`, `displayname`, `picture`, `unit`, `price`) VALUES ('',1,'coconut','Coconut','images/vegetables/coconut.jpg','piece',1000);
INSERT INTO `tblitem`(`ID`, `category_ID`, `name`, `displayname`, `picture`, `unit`, `price`) VALUES ('',1,'cucumber','Cucumber','images/vegetables/cucumber.jpg','kg',1500);
INSERT INTO `tblitem`(`ID`, `category_ID`, `name`, `displayname`, `picture`, `unit`, `price`) VALUES ('',1,'whitepicklecucumber','White Pickle Cucumber','images/vegetables/whitepicklecucumber.jpg','kg',2500);     INSERT INTO `tblitem`(`ID`, `category_ID`, `name`, `displayname`, `picture`, `unit`, `price`) VALUES ('',1,'eggplantlarge','Egg Plant (large)','images/vegetables/eggplantlarge.jpg','kg',1500);
INSERT INTO `tblitem`(`ID`, `category_ID`, `name`, `displayname`, `picture`, `unit`, `price`) VALUES ('',1,'eggplantsmall','Egg Plant (small)','images/vegetables/eggplantsmall.jpg','kg',1500);
INSERT INTO `tblitem`(`ID`, `category_ID`, `name`, `displayname`, `picture`, `unit`, `price`) VALUES ('',1,'ginger','Ginger','images/vegetables/ginger.jpg','kg',5000);     
INSERT INTO `tblitem`(`ID`, `category_ID`, `name`, `displayname`, `picture`, `unit`, `price`) VALUES ('',1,'greenbeans','Green Beans','images/vegetables/greenbeans.jpg','kg',3000);
INSERT INTO `tblitem`(`ID`, `category_ID`, `name`, `displayname`, `picture`, `unit`, `price`) VALUES ('',1,'greencookingbananas','Green Cooking Bananas','images/vegetables/greencookingbananas.jpg','piece',300);
INSERT INTO `tblitem`(`ID`, `category_ID`, `name`, `displayname`, `picture`, `unit`, `price`) VALUES ('',1,'kale','Kale ','images/vegetables/kale.jpg','bunch',700);
INSERT INTO `tblitem`(`ID`, `category_ID`, `name`, `displayname`, `picture`, `unit`, `price`) VALUES ('',1,'leeks','Leeks','images/vegetables/leeks.jpg','bunch',1000);
INSERT INTO `tblitem`(`ID`, `category_ID`, `name`, `displayname`, `picture`, `unit`, `price`) VALUES ('',1,'iceburglettuce','Iceburg Lettuce','images/vegetables/iceburglettuce.jpg','kg',2500);
INSERT INTO `tblitem`(`ID`, `category_ID`, `name`, `displayname`, `picture`, `unit`, `price`) VALUES ('',1,'softlettuce','Soft Lettuce','images/vegetables/softlettuce.jpg','bunch',1000);
INSERT INTO `tblitem`(`ID`, `category_ID`, `name`, `displayname`, `picture`, `unit`, `price`) VALUES ('',1,'okraladiesfingers','Okra (Ladies Fingers)','images/vegetables/okraladiesfingers.jpg','kg',2000);
INSERT INTO `tblitem`(`ID`, `category_ID`, `name`, `displayname`, `picture`, `unit`, `price`) VALUES ('',1,'peas','Peas','images/vegetables/peas.jpg','kg',8000);
INSERT INTO `tblitem`(`ID`, `category_ID`, `name`, `displayname`, `picture`, `unit`, `price`) VALUES ('',1,'pumpkin','Pumpkin','images/vegetables/pumpkin.jpg','piece',3000);
INSERT INTO `tblitem`(`ID`, `category_ID`, `name`, `displayname`, `picture`, `unit`, `price`) VALUES ('',1,'redonions','Red Onions','images/vegetables/redonions.jpg','kg',2000);
INSERT INTO `tblitem`(`ID`, `category_ID`, `name`, `displayname`, `picture`, `unit`, `price`) VALUES ('',1,'whiteonions','White Onions','images/vegetables/whiteonions.jpg','kg',4000);
INSERT INTO `tblitem`(`ID`, `category_ID`, `name`, `displayname`, `picture`, `unit`, `price`) VALUES ('',1,'redirishpotatoes','Red Irish Potatoes','images/vegetables/redirishpotatoes.jpg','kg',1200);
INSERT INTO `tblitem`(`ID`, `category_ID`, `name`, `displayname`, `picture`, `unit`, `price`) VALUES ('',1,'sweetpotatoes','Sweet Potatoes','images/vegetables/sweetpotatoes.jpg','kg',1500);
INSERT INTO `tblitem`(`ID`, `category_ID`, `name`, `displayname`, `picture`, `unit`, `price`) VALUES ('',1,'whiteirishpotatoes','White Irish Potatoes','images/vegetables/whiteirishpotatoes.jpg','kg',1200);
INSERT INTO `tblitem`(`ID`, `category_ID`, `name`, `displayname`, `picture`, `unit`, `price`) VALUES ('',1,'redradish','Red Radish','images/vegetables/redradish.jpg','bunch',2600);
INSERT INTO `tblitem`(`ID`, `category_ID`, `name`, `displayname`, `picture`, `unit`, `price`) VALUES ('',1,'whiteradish','White Radish','images/vegetables/whiteradish.jpg','kg',2000);
INSERT INTO `tblitem`(`ID`, `category_ID`, `name`, `displayname`, `picture`, `unit`, `price`) VALUES ('',1,'spinachswisschard','Spinach (Swiss Chard)','images/vegetables/spinachswisschard.jpg','bunch',1000);
INSERT INTO `tblitem`(`ID`, `category_ID`, `name`, `displayname`, `picture`, `unit`, `price`) VALUES ('',1,'springonions','Spring Onions','images/vegetables/springonions.jpg','bunch',500);
INSERT INTO `tblitem`(`ID`, `category_ID`, `name`, `displayname`, `picture`, `unit`, `price`) VALUES ('',1,'plumtomatoes','Plum Tomatoes','images/vegetables/plumtomatoes.jpg','kg',2000);
INSERT INTO `tblitem`(`ID`, `category_ID`, `name`, `displayname`, `picture`, `unit`, `price`) VALUES ('',1,'queentomatoes','Queen Tomatoes','images/vegetables/queentomatoes.jpg','kg',1000);
INSERT INTO `tblitem`(`ID`, `category_ID`, `name`, `displayname`, `picture`, `unit`, `price`) VALUES ('',1,'zucchini','Zucchini','images/vegetables/zucchini.jpg','piece',3000);